In [1]:
import numpy as np

In [2]:
# 1D array creation

arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr)) # to chake the type
print(arr.ndim) # to check the dimension of data
print(arr.shape) # to check the shape
print(arr.max()) # to find max in array
print(arr.min()) # to find min in array

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1
(7,)
7
1


In [3]:
# 2D array creation

arr = np.array([[1,2],[4,5],[6,7]])
print(arr)
print(type(arr)) # to chake the type
print(arr.ndim) # to check the dimension of data
print(arr.shape) # to check the shape
print(arr.max()) # to find max in array
print(arr.min()) # to find min in array

[[1 2]
 [4 5]
 [6 7]]
<class 'numpy.ndarray'>
2
(3, 2)
7
1


In [4]:
# 3D array creation

arr = np.array([[[1,2],[4,5],[6,7]]])
print(arr)
print(type(arr)) # to chake the type
print(arr.ndim) # to check the dimension of data
print(arr.shape) # to check the shape
print(arr.max()) # to find max in array
print(arr.min()) # to find min in array

[[[1 2]
  [4 5]
  [6 7]]]
<class 'numpy.ndarray'>
3
(1, 3, 2)
7
1


In [5]:
# create a nd array with this shape (3,2,2)

arr = np.array([[[1,2],[4,5]],
               [[1,2],[4,5]],
               [[1,2],[4,5]]])
print(arr.shape) 

(3, 2, 2)


In [6]:
# create an array with this shape (3,4,2,2)

import numpy as np
arr1=np.arange(1,49)
print(arr1)
print(type(arr1)) # to chake the type
print(arr1.ndim) # to check the dimension of data
print(arr1.shape) # to check the shape
print(arr1.max()) # to find max in array
print(arr1.min()) # to find min in array
arr1=arr1.reshape((3,4,2,2))
print(arr1)
print(arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
<class 'numpy.ndarray'>
1
(48,)
48
1
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]

  [[25 26]
   [27 28]]

  [[29 30]
   [31 32]]]


 [[[33 34]
   [35 36]]

  [[37 38]
   [39 40]]

  [[41 42]
   [43 44]]

  [[45 46]
   [47 48]]]]
(3, 4, 2, 2)


In [7]:
 # to fill all the element with "5" used for overwrite on existing one

import numpy as np
arr1=np.arange(1,11)
arr1.fill(5)
print(arr1)

[5 5 5 5 5 5 5 5 5 5]


In [8]:
#fill all the element with float "6"

arr2=np.full((3,4,2),6,dtype=float) 
print(arr2)

[[[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]]


In [9]:
#here the default dtype is "0"

zero=np.zeros((5,4),dtype=int) 
print(zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
 #here the default dtype is "1"
    
one=np.ones((4,5),dtype=int)
print(one)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
# create indentity matrix

import numpy as np
eye=np.eye(4,5,dtype=int) 
print(eye)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [12]:
# axis =0 append on column

eye=np.eye(4,4,dtype=int) # create indentity matrix
# one=np.ones((4,5),dtype=int) 
# print(eye)
print(np.append(eye,np.arange(16).reshape((4,4)),axis=0))

[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
# axis =1 append on row

eye=np.eye(4,4,dtype=int) # create indentity matrix
print(np.append(eye,np.arange(16).reshape((4,4)),axis=1)) 

[[ 1  0  0  0  0  1  2  3]
 [ 0  1  0  0  4  5  6  7]
 [ 0  0  1  0  8  9 10 11]
 [ 0  0  0  1 12 13 14 15]]


In [14]:
# concatenate are used to concatenate the two or more than two array at once

eye = np.eye(4, dtype=int)  # create identity matrix
arr1 = np.arange(16).reshape((4, 4))  # create a 4x4 array
arr2 = np.arange(16).reshape((4, 4)) 
concatenated = np.concatenate([eye, arr1,arr2], axis=1)  # Concatenate along columns
print(concatenated)
print(np.info(concatenated)) #for complete information about given array

[[ 1  0  0  0  0  1  2  3  0  1  2  3]
 [ 0  1  0  0  4  5  6  7  4  5  6  7]
 [ 0  0  1  0  8  9 10 11  8  9 10 11]
 [ 0  0  0  1 12 13 14 15 12 13 14 15]]
class:  ndarray
shape:  (4, 12)
strides:  (48, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x23526fba240
byteorder:  little
byteswap:  False
type: int32
None


In [15]:
# dot matrix multiplication 

out=np.dot(np.array([[1,2],[3,4]]),np.array([[6,7],[8,9]]))
print(out)

[[22 25]
 [50 57]]


In [16]:
# dot matrix multiplication with transpose the second array

import numpy as np
out=np.dot(np.array([[6,7],[8,9]]),np.array([[1,2],[3,4],[5,6]]).T)
print(out)

[[20 46 72]
 [26 60 94]]


In [17]:
'''ask the user to enter the number:5
1 2 3 4 5
5 6 7 8 9
2 4 6 8 9
5 6 7 8 9
2 4 6 8 9
combine all element in above and make a shape with (5,5) as array

'''
array=[]
for x in range(int(input("enter a number :"))):
    out=[int(j) for j in input().split()]
    array.append(out)
else:
    array=np.array(array)
    print(array)
    print(array.shape)

enter a number :5
1 2 3 4 5
5 6 7 8 9
2 4 6 8 9
5 6 7 8 9
2 4 6 8 9
[[1 2 3 4 5]
 [5 6 7 8 9]
 [2 4 6 8 9]
 [5 6 7 8 9]
 [2 4 6 8 9]]
(5, 5)


In [18]:
out=np.dot(np.array([[6,7],[8,9]]),np.array([[1,2],[3,4],[5,6]]).T)
print(out)
# np.save("data.txt",out) # store data in binary formate
np.savetxt("data.txt",out) #save data with .npy extension
# we can also use delimeter np.savetxt("data.txt",out,delimeter=',') 

[[20 46 72]
 [26 60 94]]


In [19]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [20]:
random_array=np.random.random(10)
print(random_array)

[0.79420766 0.31799381 0.49968328 0.09351561 0.02925394 0.49771241
 0.14307338 0.40321509 0.88932119 0.0097174 ]


In [21]:
# 10 number randomly generated in between 5 and 20

print(np.random.randint(5,20,10))

[11  5 13 10 16 18 10 14  9 14]
